### ISSUE TITLE
go get Is not Working 

### ISSUE THREAD

**Issue by gorfadvijay** [jz222/loggy#5]
go get is not working

its giving error 
can't load package: package .: no Go files in dir

**Comment by jz222** [comment]
Create the following directories `$HOME/go/src/github.com/jz222/`. You maybe already have a `github.com` folder if you installed other Go code from `github.com`. Then open the directory in your terminal with `cd $HOME/go/src/github.com/jz222`. Now you can clone the code with `git clone https://github.com/jz222/loggy.git`. The LOGGY code should then be in `$HOME/go/src/github.com/jz222/loggy`. Finally, you can navigate into the `loggy` directory with `cd loggy` and install the dependencies with `go get`.

**Comment by gorfadvijay** [comment]
not working for me 
could you send me some resource from which i can uninstall go , reinstall Go workbench with valid configuration

**Comment by jz222** [comment]
Unfortunately, I can't help you with that, since I don't know your system and your personal needs. If you google, you will find plenty of guides that help you setting up your workbench correctly. Once you installed Go correctly, you can verify your setup with `go env`. Afterwards, you can proceed as described above.
