### ISSUE TITLE
Issue in Docker

### ISSUE THREAD

**Issue by gorfadvijay** [jz222/loggy#6]
docker run \
--env PORT=2800 \
--env SECRET=secret \
--env MONGO_URI=mongodb://admin:password0@ds263108.mlab.com:63108/loggy-test\?retryWrites=false \
--env MONGO_DB_NAME=loggy-test \
--env IS_SELFHOSTED=true \
-p 2800:2800 \
-it \
jz222/loggy:0.1.0
is not working 
giving error : 
2020/04/13 07:59:07 Could not load .env file. Proceeding to read environment variable
2020/04/13 07:59:07 Could not load .env file. Proceeding to read environment variable
2020/04/13 07:59:07 Could not load .env file. Proceeding to read environment variable
2020/04/13 07:59:11 ❌connection() : auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.

**Comment by jz222** [comment]
You have to provide your own database connection string. The connection string `MONGO_URI=mongodb://admin:password0@ds263108.mlab.com:63108/loggy-test?retryWrites=false` that you used was my personal database for testing. I, of course, deleted the database before publishing it so that nobody else can access my personal database.

You can create your own managed database on mLab or you set up a local MongoDB.

**Comment by gorfadvijay** [comment]
yes i know it , i have my database , but its giving error
2020/04/13 07:59:07 Could not load .env file. Proceeding to read environment variable

**Comment by jz222** [comment]
`2020/04/13 07:59:07 Could not load .env file. Proceeding to read environment variable` is not an error, just an information. However, I already thought this will be misleading without any context. It just means that there was no `.env` file and it proceeds to read the environment variables without loading them from an `.env` file first. I created another [issue](https://github.com/jz222/loggy/issues/7) to make this clearer.

`connection() : auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.` Currently, the server does not use SSL to connect to MongoDB. Disabling SSL should fix it. Can you please tell me how you are using MongoDB? Are you using a local installation of MongoDB? I'm planning to add SSL soon and will provide an extensive guide on how to set it up.

**Comment by gorfadvijay** [comment]
Failed to connect to MongoDB with error: context deadline exceeded

**Comment by gorfadvijay** [comment]
Docker build giving a same error 
Failed to connect to MongoDB with error: context deadline exceeded

**Comment by jz222** [comment]
Yesterday, I published version 0.3.2, which contains CA files. I tested it with managed MongoDB instances on mLab and Atlas. I've also tested it with SSL enabled and disabled.

If you tell me your MongoDB setup and configuration, I can have a look.

**Comment by gorfadvijay** [comment]
@jz222 yes i have used 0.3.2 version itselft , fixed when i used mlab instance , before i was using mongo:latest image in local docker environment in that db error was throwing 
after shifting to mlab instances error is solved , can you find solution for locally hosted mongodb database
thank you tho !

**Comment by jz222** [comment]
If you run LOGGY as Docker container, its `localhost` will refer to the `localhost` of the container and not the localhost of your machine. To connect the LOGGY container to the MongoDB container, you can create a network. [Here](https://medium.com/@jaaq/making-docker-containers-talk-to-each-other-by-hostname-using-container-networking-94835a6f6a5b) you can find an article on this topic.

Before you create a network, stop the LOGGY and MongoDB containers. Then create a network with `docker network create loggyNetwork`. Afterwards, run the MongoDB container with the flags `--name mongodb --network loggyNetwork` and the LOGGY container with the flag `--network loggyNetwork`. Instead of `localhost` in the `MONGO_URI` use `mongodb`.

This is my local setup:

**MongoDB:**
```
docker run \
-d \
-it \
-p 27017:27017 \
--name mongodb \
--network loggyNetwork \
-v ~/data/mongodb.conf:/etc/mongodb.conf \
-v ~/data/db:/data/db \
mongo -f /etc/mongodb.conf
```

**LOGGY:**
```
docker run \
--env PORT=2800 \
--env SECRET=secret \
--env MONGO_URI=mongodb://user:password@mongodb/loggy\?retryWrites=false \
--env MONGO_DB_NAME=loggy \
--env CLIENT_URL=http://localhost:3000 \
--env IS_SELFHOSTED=true \
--network loggyNetwork \
-p 2800:2800 \
-it \
jz222/loggy:0.3.2
```

**Comment by gorfadvijay** [comment]
thank you @jz222 
working now

**Comment by gorfadvijay** [comment]
thank you @jz222
working now
